### ISSUE TITLE
Lantern website is currently down...

### ISSUE THREAD

**Issue by cheez26** [evancwright/Lantern#1]
I don't know if you can see this, but your website is probably down. All I get is a "Not Found" and that's probably not good.

**Comment by evancwright** [comment]
Is it still down? I just accessed it from my phone?  Thank you for letting me know. My direct email is ***@***.***


Sent from Yahoo Mail for iPhone


On Monday, July 22, 2024, 8:45 PM, Chelsea E. ***@***.***> wrote:




I don't know if you can see this, but your website is probably down. All I get is a "Not Found" and that's probably not good.

**Comment by evancwright** [comment]
Just to confirm the URL is https://textadventure.net

**Comment by cheez26** [comment]
> Just to confirm the URL is https://textadventure.net

Ah, so it just moved to a different URL than I thought. Thanks.

**Comment by cheez26** [comment]
Yeah, the site works. Thanks again.
